<?php

namespace JuniorISEP\VitrineBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{


  public function findArticle($section, $order, $page, $rb){

    if (in_array($section, array(1,2,3))){
      $tb = $rb->brandFilter(1,$order);
    }
    elseif (in_array($section, array(4,5,6,7))){
      $tb = $rb->brandFilter(2,$order);
    }
    elseif (in_array($section, array(8,9,10,16))){
      $tb = $rb->brandFilter(3,$order);
    }
    if (in_array($section, array(11,12,13,14,15))){
      $tb = $rb->brandFilter(4,$order);
    }



    if($order == 'default'){
      $listArticles = $this->findBy(
        array('section' => $section),
        array(),
        8,
        ($page-1)*8
      );
    }
    else{
      $listArticles = $this->findBy(
        array('section' => $section, 'brand' => $tb),
        array(),
        8,
        ($page-1)*8
      );

    }

    return $listArticles;
  }


}
