<?php

namespace JuniorISEP\VitrineBundle\Repository;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRepository extends \Doctrine\ORM\EntityRepository
{

  public function brandFilter($cat, $letter){
    $brandList;

    switch ($cat) {
      case 1:
        $brandList = $this->findBy(
        array('dispTabac' => 1)
        );
        break;
      case 2:
        $brandList = $this->findBy(
        array('dispCigaretteElec' => 1)
        );
        break;
      case 3:
        $brandList = $this->findBy(
        array('dispAccessoires' => 1)
        );
        break;
      case 4:
        $brandList = $this->findBy(
        array('dispAlcools' => 1)
        );
        break;

    }
    $tab = array();
    foreach ($brandList as $brand) {
      if(strtolower($brand->getName()[0])== strtolower($letter)){
        array_push($tab,$brand->getId());
      }

    }

    return $tab;


  }
}
