<?php

namespace JuniorISEP\VitrineBundle\Repository;

/**
 * InfosContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfosContactRepository extends \Doctrine\ORM\EntityRepository
{
}
