<?php

namespace JuniorISEP\VitrineBundle\Repository;

/**
 * MentionsLegalesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MentionsLegalesRepository extends \Doctrine\ORM\EntityRepository
{
}
