junior_isep_vitrine:
    resource: "@JuniorISEPVitrineBundle/Resources/config/routing.yml"
    prefix:   /


app:
    resource: '@AppBundle/Controller/'
    type: annotation

login:
    path: /login
    defaults:
        _controller: JuniorISEPUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout
