<?php

namespace JuniorISEP\UserBundle\Repository;

/**
 * logsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class logsRepository extends \Doctrine\ORM\EntityRepository
{
}
