services:
  JuniorISEP\UserBundle\DataFixtures\ORM\LoadUser:
        tags: [doctrine.fixture.orm]
#    junior_isep_user.example:
#        class: JuniorISEP\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
